# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/shm-anomaly-detection',
                'doc_host': 'https://justforprogramming07-code.github.io',
                'git_url': 'https://github.com/justforprogramming07-code/shm-anomaly-detection',
                'lib_path': 'shm_anomaly_detection'},
  'syms': {'shm_anomaly_detection.core': {'shm_anomaly_detection.core.foo': ('core.html#foo', 'shm_anomaly_detection/core.py')}}}
